### ISSUE TITLE
Add support for xrate and xincrease

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/promql-engine#192]
There seems to be a need in the Prometheus community to have rate/increase functions that do not do extrapolation. 

We briefly discussed this in Slack and we think there's value to add support for these functions in the Thanos engine. @GiedriusS mentioned they already maintain a fork for `xrate/xincrease` which we can either integrate or use as a starting point.

* Slack thread: https://cloud-native.slack.com/archives/CL25937SP/p1677487566632769
* Fork with `xrate` support: https://github.com/vinted/prometheus/commit/835de212f1022e4be7d18af5a0dd1f1c8589adce#diff-ad2761bb162a2f12326b18f2714ef54f4cd476cfe3388f77b2b20c5ff82e4faaR1893-R1994.

**Comment by yeya24** [comment]
So those functions will be under a feature flag?

**Comment by fpetkovski** [comment]
I think [this](https://github.com/thanos-community/promql-engine/pull/216/files#diff-2e6c4934f63ff9b712c2c346b33036af4724adf70b0801fff9b74f71b37fcd89R139-R142) might be solving that problem, but we should test what happens.

**Comment by yeya24** [comment]
Can we close this now? I think we already added support for x functions

**Comment by fpetkovski** [comment]
Yes, closing.

**Comment by sathieu** [comment]
Is there documentation for those new functions ?

**Comment by fpetkovski** [comment]
These functions are implemented based on a quite old issue in Prometheus: 
* https://github.com/prometheus/prometheus/issues/3806
* https://docs.google.com/document/d/1y2Mp041_2v0blnKnZk7keCnJZICeK2YWUQuXH_m4DVc/edit

The short summary is that they don't do extrapolation so you can get exact rate calculations which is useful for sparse metrics.

For example, if a metric goes up by 1 every hour or so, the `rate` function will extrapolate and you might see something like `1.1` as the result. On the other hand, `xrate` will show you exactly `1`.

I agree it would be nice to have some documentation around this 👍

**Comment by sathieu** [comment]
Thanks @fpetkovski.

I was wondering if the `xincrease` function would be able to trigger an alert on a new metric. My specific usecase is described [here](https://community.cloudogu.com/t/continuously-scan-your-kubernetes-cluster-for-security-issues-using-trivy-operator/962#alerting-4).

NB: we currently use plain prometheus.

**Comment by fpetkovski** [comment]
Yes, `xincrease` would inject a 0 value for a newly appearing counter, so even applying it to 1 sample will produce a result.
