### ISSUE TITLE
Add support for timestamp function

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/promql-engine#206]
The timestamp function is currently broken and we've decided to revert it in https://github.com/thanos-community/promql-engine/pull/204.

The correct way to implement it is to return each sample's timestamp instead of the step timestamp. This will make sure that samples returned due to the engine lookback have their original timestamp in the output. 

One way to do it is to detect the presence of a the `timestamp` function in a query (maybe through an optimizer), and push it down into the vector selector. The selector will then store timestamps directly into the values of output vectors.

**Comment by nishchay-veer** [comment]
Hey @fpetkovski I've a good understanding of tests in GO . Can you please assign this to me so I could work on this ?

**Comment by nishchay-veer** [comment]
Could you provide guidance on the modifications I should make?

**Comment by fpetkovski** [comment]
Closed by https://github.com/thanos-io/promql-engine/pull/366
