### ISSUE TITLE
Remove vendored version of PromQL parser

### ISSUE THREAD

**Issue by fpetkovski** [thanos-io/promql-engine#295]
We currently use a vendored version of the Prometheus PromQL parser in order to inject support for functions.

Now that https://github.com/prometheus/prometheus/pull/12170 is merged, we can remove the vendored code and create a parser instance with the custom `xrate`/`xincrease`/`xdelta` functions.

**Comment by Player256** [comment]
@fpetkovski I am interested to solve this issue. It would be helpful if you can guide me.

**Comment by abn15** [comment]
i am interested to contribute, would love to look into this issue and resolve.

**Comment by Vanshikav123** [comment]
Hello @fpetkovski I hope this message finds you well. I'm excited to introduce myself as a new member of the Thanos community. I'm eager to contribute to the organization and help enhance the project. If possible, could you please consider assigning me this issue , I am also open to any guidance or feedback you can provide during the process.

**Comment by yeya24** [comment]
There is already a pr opened to fix this https://github.com/thanos-io/promql-engine/pull/305

**Comment by fpetkovski** [comment]
Closed via https://github.com/thanos-io/promql-engine/pull/305.
