### ISSUE TITLE
Failed to query metric name with time slice name

### ISSUE THREAD

**Issue by yutian1224** [thanos-io/promql-engine#313]
I recorded some metrics with name like **xxx:xxx:xxx:1m**
They can be search in prometheus engine,but failed in thanos engine

![image](https://github.com/thanos-io/promql-engine/assets/13673671/7069dbd7-cad0-4c9f-bbcf-4b47cd23f3a1)

**Comment by MichaHoffmann** [comment]
Hey, which version of thanos are you using?

**Comment by GiedriusS** [comment]
It's probably same like https://github.com/thanos-io/thanos/issues/6677. I suggest moving this issue there
