### ISSUE TITLE
Implement aggregation operations

### ISSUE THREAD

**Issue by sharadgaur** [thanos-io/promql-engine#41]
Following functions need to be implemented:

* [x] group (all values in the resulting vector are 1)~
* [x] stddev (calculate population standard deviation over dimensions)
* [x] stdvar (calculate population standard variance over dimensions)
* [x] count (count number of elements in the vector)~
* [x] count_values (count number of elements with the same value)
* [x] bottomk (smallest k elements by sample value)
* [x] topk (largest k elements by sample value)
* [x] quantile

**Comment by yeya24** [comment]
One note here, we have `group` and `count` already.
It is easier to start with `stddev` and `stdvar` as they takes a range vector only, while `count_values`, `bottomk` and `topk` need to take additional parameters so probably we can wait for https://github.com/thanos-community/promql-engine/issues/23

**Comment by alanprot** [comment]
Hi,

I did not see this issue before so i opened a [new one](https://github.com/thanos-community/promql-engine/issues/105) for bottomK and topK. Those aggregations seems to need some additional work so i think it should be fine to track those there?

**Comment by MichaHoffmann** [comment]
Closing as all aggregations are added nowadays!
