### ISSUE TITLE
Optimize Equinix usage

### ISSUE THREAD

**Issue by jeefy** [thanos-io/promql-engine#448]
Hello! Friendly neighborhood CNCF person here.

We're looking to reduce Equinix usage where possible. This is all related to https://contribute.cncf.io/resources/newsletters/2024-02-21-projectnewsletter/#equinix-updates and the resource usage policy linked further below. :)

We see you're using both a pretty beefy machine that, based on bandwidth alone, looks to sit mostly idle. Since these are bare-metal machines, could you instead tear down that machine and only spin something like that up when a benchmark actually needs to run? :) 

Additionally, is there a reason you're running a dedicated GHA runner instead of using the GitHub provided runners? 

Thanks!

cc @vielmetti (Awesome Equinix staffer :sunglasses:)

**Comment by GiedriusS** [comment]
Thank you for the message and sorry for the problems. I wanted to use on-demand provisioned physical servers but never found the time to implement this. Currently it runs our continuous benchmarking job but it has been broken for a long time - the website doesn't show newest entries, it sometimes times out or even gets OOM killed. Given that it's basically unmaintained, I think we can just destroy the machine/job and get back to it when we have the time to do it properly. @fpetkovski do you have any thoughts?

**Comment by fpetkovski** [comment]
Decomissioning the machine for now makes sense. I think we should go back to running our light weight benchmarks using shared GH runners and we can reconsider a dedicated machine if we need it again.

**Comment by GiedriusS** [comment]
https://github.com/thanos-io/promql-engine/pull/449

**Comment by vielmetti** [comment]
Thank you!
