### ISSUE TITLE
Add testcases to cover error scenarios

### ISSUE THREAD

**Issue by saswatamcode** [thanos-io/promql-engine#88]
It would be a good idea to test error cases to make sure that the parts implemented have fully compliant error modes with the old engine.

Also, under certain circumstances, queries may return NaN values, which are hard to compare via `reflect.DeepEqual` used by `testutil.Equals`, so having a special test case for that would be great. For example queries like `scalar(http_request_total)` return NaN if vectors have more than one value.

**Comment by saswatamcode** [comment]
Raised https://github.com/efficientgo/core/pull/3 for NaN support! cc:@bwplotka 🙂

**Comment by yeya24** [comment]
Is this something we can close now? Fuzzing test should cover error scenarios

**Comment by saswatamcode** [comment]
Yes I think we can close
